backend:
  name: github
  repo: Jim247/tplatform
  branch: master

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'blog'
    label: 'Blog Posts'
    folder: 'src/app/blog/posts'
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'James Burgess' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'blog-2023'
    label: 'Blog Posts 2023'
    folder: 'src/app/blog/posts/2023'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'James Burgess' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'blog-2024'
    label: 'Blog Posts 2024'
    folder: 'src/app/blog/posts/2024'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD' }
      - { label: 'Author', name: 'author', widget: 'string', default: 'James Burgess' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
